site_name: Rake Up Eagle
site_description: A day of service to disabled, veteran, and senior citizens.  Sponsored by Eagle Middle School PTO.
site_author: Eagle Middle School PTO
theme:
  name: material
  custom_dir: overrides
  logo: images/logo.png
docs_dir: website
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
