site_name: Rake Up Eagle
repo_url: https://github.com/rakeupeagle/rakeupeagle
site_description: A day of service to disabled, veteran, and senior citizens.  Sponsored by Eagle Middle School PTO.
site_author: Eagle Middle School PTO
copyright: David Binetti 2025
theme:
  name: material
  logo: images/logo.png
docs_dir: website
markdown_extensions:
  - attr_list
