[project]
name = "rakeupeagle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "David Binetti", email = "dbinetti@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "mkdocs",
    "mkdocs-material",
]

[project.scripts]
rakeupeagle = "rakeupeagle:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
