from pyflowchart import *

start = StartNode("Start")
op_create_current_event = OperationNode('Create Current Event')
op_copy_elements = OperationNode('Copy Recipients/Teams from Last Year')
op_send_invitations = OperationNode('Send Invitations')
sub_process_invite_responses = SubroutineNode('Process Invite Responses')
op_send_reminders = OperationNode('Send Reminders Week Of')
sub_process_reminder_responses = SubroutineNode('Process Responses')
op_send_start = OperationNode('Send Event Starting Morning Of')
sub_process_start_responses = SubroutineNode('Process Responses')
op_send_finish = OperationNode('Send Event Finishing Afternoon Of')
sub_process_finish_responses = SubroutineNode('Process Finishing Responses')
# cond = ConditionNode('Yes or No?')
# io = InputOutputNode(InputOutputNode.OUTPUT, 'something...')
end = EndNode("End")

start.connect(op_create_current_event)
op_create_current_event.connect(op_copy_elements)
op_copy_elements.connect(op_send_invitations)
op_send_invitations.connect(sub_process_invite_responses)
sub_process_invite_responses.connect(op_send_reminders)
op_send_reminders.connect(sub_process_reminder_responses)
sub_process_reminder_responses.connect(op_send_start)
op_send_start.connect(sub_process_start_responses)
sub_process_start_responses.connect(op_send_finish)
op_send_finish.connect(sub_process_finish_responses)
sub_process_finish_responses.connect(end)


fc = Flowchart(start)
