# Generated by Django 3.2.9 on 2021-11-27 16:52

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import hashid_field.field
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('data', models.JSONField(editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('phone',),
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_app.account_set+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('state', django_fsm.FSMIntegerField(choices=[(0, 'New'), (10, 'Active'), (20, 'Archived')], default=0)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('deadline', models.DateField()),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.account')),
                ('state', django_fsm.FSMIntegerField(choices=[(-20, 'Cancelled'), (-10, 'Excluded'), (0, 'New'), (10, 'Included'), (20, 'Confirmed')], default=0)),
                ('size', models.IntegerField(blank=True, choices=[(110, 'Small (1-15 bags)'), (120, 'Medium (16-30 bags)'), (130, 'Large (31+ bags)')], help_text='Please provide the approximate yard size.')),
                ('location', models.CharField(blank=True, default='', help_text='Please provide the location address to be raked.', max_length=512)),
                ('place', models.CharField(blank=True, default='', max_length=255)),
                ('is_precise', models.BooleanField(default=False)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('geocode', models.JSONField(blank=True, null=True)),
                ('is_dog', models.BooleanField(blank=True, default=False, help_text='If you have a dog, it must be contained in your home for us to rake. <em>Also, you must clean up all animal waste before we arrive or our team group will not be able to rake.</em>')),
                ('notes', models.TextField(blank=True, default='', help_text='Please add any other notes you think we should know.', max_length=2000)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Administrator Notes (from calling).', max_length=2000)),
                ('bags', models.IntegerField(blank=True, help_text='Actual Bags Used', null=True)),
                ('hours', models.FloatField(blank=True, help_text='Actual Hours Worked', null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.account',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.account')),
                ('state', django_fsm.FSMIntegerField(choices=[(-20, 'Cancelled'), (-10, 'Excluded'), (0, 'New'), (10, 'Included'), (20, 'Confirmed')], default=0)),
                ('size', models.IntegerField(choices=[(105, 'Solo (1 Adult)'), (110, 'Extra-Small (2-5 Adults)'), (120, 'Small (6-10 Adults)'), (130, 'Medium (11-15 Adults)'), (140, 'Large (16-20 Adults)'), (150, 'Extra-Large (21+ Adults)')], help_text='The size of your group. (Number of adults, or equivalent in children.)')),
                ('nickname', models.CharField(blank=True, default='', help_text="Whimsical Team Name (ie, Robert's Rakers, Covey Courters, etc.)", max_length=100)),
                ('reference', models.CharField(blank=True, default='', help_text='How did you hear about us?', max_length=512)),
                ('actual', models.IntegerField(blank=True, help_text='The actual number of adults, or adult-equivalent in children.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes.', max_length=512)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Administrator Notes (from calling).', max_length=2000)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.account',),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('state', django_fsm.FSMIntegerField(choices=[(0, 'New'), (10, 'Sent')], default=0)),
                ('sid', models.CharField(blank=True, max_length=100)),
                ('to_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('from_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('body', models.TextField(blank=True)),
                ('direction', models.IntegerField(blank=True, choices=[(10, 'Inbound'), (20, 'Outbound')], null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('state', django_fsm.FSMIntegerField(choices=[(0, 'New')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.recipient')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.team')),
            ],
        ),
    ]
