# Generated by Django 3.1.2 on 2020-10-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='name',
            field=models.CharField(default='', help_text='Your name (or group name).', max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='number',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five +')], help_text='Number in Group.'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(default='', help_text='Your mobile phone.', max_length=255),
        ),
    ]
