# Generated by Django 3.2.9 on 2021-11-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
