# Generated by Django 3.2.8 on 2021-10-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='team',
            field=models.CharField(blank=True, default='', help_text="Team Name (ie, Robert's Rakers, Covey Courters, etc.) (optional)", max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='reference',
            field=models.TextField(blank=True, default='', help_text='How did you hear about us? (optional)', max_length=512),
        ),
    ]
