# Generated by Django 3.1.2 on 2020-10-13 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201012_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(default='', help_text='Your email address.', max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='number',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five +')], help_text='Number in your group.'),
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('size', models.IntegerField(choices=[(110, 'Small (1-15 bags)'), (120, 'Medium (16-30 bags'), (130, 'Large (35+ bags)')])),
                ('name', models.CharField(default='', help_text='Your name.', max_length=255)),
                ('address', models.CharField(default='', help_text='Your street address (must be in Eagle).', max_length=255)),
                ('email', models.EmailField(default='', help_text='Your email.', max_length=254)),
                ('phone', models.CharField(default='', help_text='Your phone.', max_length=255)),
                ('is_verified', models.BooleanField(help_text='Are you age 65 or older, disabled, or veteran?')),
                ('is_dog', models.BooleanField(help_text='Do you have a dog?')),
                ('is_waiver', models.BooleanField()),
                ('notes', models.TextField(blank=True, default='', help_text='Please add any other notes you think we should know.', max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'New'), (10, 'Pending'), (20, 'Accepted'), (30, 'Rejected')], default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='app.recipient')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='app.volunteer')),
            ],
        ),
    ]
