# Generated by Django 3.2.8 on 2021-10-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211006_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='reference',
            field=models.CharField(blank=True, default='', help_text='How did you hear about us? (optional)', max_length=512),
        ),
    ]
