# Generated by Django 5.1.1 on 2024-09-14 15:59

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_recipient_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Your mobile number.', max_length=128, null=True, region=None),
        ),
    ]
