# Generated by Django 3.2.8 on 2021-10-07 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_volunteer_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='app.account'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='is_dog',
            field=models.BooleanField(blank=True, default=False, help_text='If you have a dog, it must be contained in your home for us to rake. <em>Also, you must clean up all animal waste before we arrive or our volunteer group will not be able to rake.</em>'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Please provide the location address to be raked.', max_length=512),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='size',
            field=models.IntegerField(blank=True, choices=[(110, 'Small (1-15 bags)'), (120, 'Medium (16-30 bags)'), (130, 'Large (31+ bags)')], help_text='Please provide the approximate yard size.'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='reference',
            field=models.CharField(blank=True, default='', help_text='How did you hear about us?', max_length=512),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='size',
            field=models.IntegerField(choices=[(110, 'Extra-Small (1-5 Adults)'), (120, 'Small (6-10 Adults)'), (130, 'Medium (11-15 Adults)'), (140, 'Large (16-20 Adults)'), (150, 'Extra-Large (21+ Adults)')], help_text='The size of your group. (Number of adults, or equivalent in children.)'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='team',
            field=models.CharField(blank=True, default='', help_text="Whimsical Team Name (ie, Robert's Rakers, Covey Courters, etc.)", max_length=100),
        ),
    ]
