# Generated by Django 3.2.8 on 2021-11-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211007_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='app.recipient'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='app.volunteer'),
        ),
    ]
