# Generated by Django 5.1.1 on 2024-09-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_recipient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='app.event'),
        ),
        migrations.AddField(
            model_name='team',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='app.event'),
        ),
    ]
