# Generated by Django 4.2.7 on 2023-11-15 22:21

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_assignment_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='recipient_state',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='team_state',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(-20, 'Failed'), (-10, 'Cancelled'), (0, 'New'), (10, 'Assigned'), (40, 'Started'), (50, 'Finished')], default=0),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(-40, 'Blocked'), (-20, 'Cancelled'), (-10, 'Inactive'), (0, 'New'), (10, 'Active'), (20, 'Confirmed'), (30, 'Assigned')], default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(-20, 'Cancelled'), (-10, 'Inactive'), (0, 'New'), (10, 'Active'), (20, 'Confirmed'), (30, 'Assigned')], default=0),
        ),
    ]
