# Generated by Django 3.2.9 on 2021-11-28 15:23

from django.db import migrations
from django.db.models import Q
def forward(apps, schema_editor):
    Thread = apps.get_model('app', 'Thread')
    Message = apps.get_model('app', 'Message')
    Account = apps.get_model('app', 'Account')

    ms = Message.objects.all()
    for m in ms:
        try:
            account = Account.objects.get(
                Q(phone=m.to_phone) |
                Q(phone=m.from_phone)
            )
        except:
            continue
        thread, _ = Thread.objects.get_or_create(
            account=account,
        )
        m.thread = thread
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_thread_topic'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
