# Generated by Django 3.1.4 on 2020-12-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201206_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='size',
            field=models.IntegerField(choices=[(110, 'Extra-Small (1-2 Adults)'), (120, 'Small (3-5 Adults)'), (130, 'Medium (5-9 Adults)'), (140, 'Large (10-15 Adults)'), (150, 'Extra-Large (15+ Adults)')], default=110, help_text='The size of your group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipient',
            name='size',
            field=models.IntegerField(choices=[(110, 'Small (1-15 bags)'), (120, 'Medium (16-30 bags)'), (130, 'Large (31+ bags)')], help_text='Yard Size'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='number',
            field=models.IntegerField(blank=True, help_text='Number in your group.', null=True),
        ),
    ]
