# Generated by Django 3.2.8 on 2021-11-06 15:07

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211106_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='event',
            field=models.ForeignKey(default=app.models.get_latest_event, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.event'),
        ),
    ]
