# Generated by Django 3.1.3 on 2020-11-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201028_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='adults',
            field=models.IntegerField(help_text='Number of adults in your group.', null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='children',
            field=models.IntegerField(help_text='Number of children in your group.', null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='number',
            field=models.IntegerField(help_text='Number in your group.', null=True),
        ),
    ]
