# Generated by Django 5.1.1 on 2024-09-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_team_phone'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipient',
            constraint=models.UniqueConstraint(fields=('phone', 'event'), name='unique_recipient_event'),
        ),
    ]
