# Generated by Django 3.2.8 on 2021-11-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_assignment_event'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('volunteer', 'recipient', 'event'), name='unique_assignment'),
        ),
    ]
