# Generated by Django 3.1.4 on 2020-12-13 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201213_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='is_waiver',
        ),
    ]
