# Generated by Django 3.1.3 on 2020-11-08 15:11

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201108_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='phone',
            field=phone_field.models.PhoneField(default='', help_text='Your phone.', max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=phone_field.models.PhoneField(default='', help_text='Your mobile phone.', max_length=255),
        ),
    ]
