# Generated by Django 4.1.1 on 2022-09-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_account_polymorphic_ctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
