# Generated by Django 5.1.1 on 2024-09-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_recipient_unique_recipient_event'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('phone', 'event'), name='unique_team_event'),
        ),
    ]
