# Generated by Django 4.2.5 on 2023-09-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_recipient_user_alter_team_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipient',
            name='is_senior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipient',
            name='is_veteran',
            field=models.BooleanField(default=False),
        ),
    ]
