# Generated by Django 3.2.8 on 2021-11-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_assignment_unique_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Administrator Notes (from calling).', max_length=2000),
        ),
    ]
