# Generated by Django 3.1.3 on 2020-11-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201108_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='adults',
            field=models.IntegerField(blank=True, help_text='Number of adults in your group.', null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='children',
            field=models.IntegerField(blank=True, help_text='Number of children in your group.', null=True),
        ),
    ]
