# Generated by Django 4.1.1 on 2022-09-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_picture_event_delete_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='thread',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
