# Generated by Django 3.1.3 on 2020-11-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201108_0716'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('recipient', 'volunteer'), name='unique_assignment'),
        ),
    ]
