# Generated by Django 3.2.7 on 2021-10-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201214_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='reference',
            field=models.TextField(blank=True, default='', help_text='How did you hear about us?', max_length=512),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='size',
            field=models.IntegerField(choices=[(110, 'Extra-Small (1-5 Adults)'), (120, 'Small (6-10 Adults)'), (130, 'Medium (11-15 Adults)'), (140, 'Large (16-20 Adults)'), (150, 'Extra-Large (21+ Adults)')], help_text='The size of your group'),
        ),
    ]
