# Generated by Django 4.1.1 on 2022-09-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_message_thread_delete_thread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
