# Generated by Django 3.1.3 on 2020-11-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201108_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notes.', max_length=512),
        ),
    ]
