# Generated by Django 4.1.1 on 2022-09-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Your full name.', max_length=100),
        ),
    ]
