# Generated by Django 4.2.6 on 2023-10-31 15:49

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_recipient_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(-30, 'Archived'), (-20, 'Cancelled'), (-10, 'Excluded'), (0, 'New'), (10, 'Included'), (20, 'Confirmed'), (30, 'Checked-In'), (40, 'Missed'), (50, 'Complete')], default=0),
        ),
    ]
