# Generated by Django 3.1.3 on 2020-11-08 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201108_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.recipient'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.volunteer'),
        ),
    ]
