# Generated by Django 4.1.1 on 2022-09-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Please provide the street address to be raked (City of Eagle is assumed).', max_length=512),
        ),
    ]
