# Generated by Django 3.2.9 on 2021-11-08 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211108_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer', to='app.account'),
        ),
    ]
