# Generated by Django 3.1.3 on 2020-11-12 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201108_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='app.recipient'),
        ),
    ]
