# Generated by Django 5.1.1 on 2024-09-17 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-created',)},
        ),
    ]
