# Generated by Django 3.1.3 on 2020-11-12 13:59

from django.db import migrations

def forward(apps, schema_editor):
    Volunteer = apps.get_model('app', 'Volunteer')
    vs = Volunteer.objects.all()
    for v in vs:
        v.recipient = v.assignments.first().recipient
        v.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_volunteer_recipient'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
