# Generated by Django 4.1.1 on 2022-10-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
