# Generated by Django 4.2.6 on 2023-11-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_assignment_bags_assignment_comments_assignment_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='rakedate',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='phone',
        ),
    ]
