# Generated by Django 3.1.3 on 2020-11-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201112_0559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
