# Generated by Django 3.2.9 on 2021-11-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_volunteer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='actual',
            field=models.IntegerField(blank=True, help_text='The actual number of adults, or adult-equivalent in children.', null=True),
        ),
    ]
