# Generated by Django 3.2.7 on 2021-10-02 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='one', to='app.recipient'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two', to='app.volunteer'),
        ),
    ]
