# Generated by Django 4.2.6 on 2023-11-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_rakedate_event_date_remove_event_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.event'),
        ),
    ]
