# Generated by Django 3.2.9 on 2021-11-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_volunteer_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Administrator Notes (from calling).', max_length=2000),
        ),
    ]
