# Generated by Django 3.1.3 on 2020-11-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='bags',
            field=models.IntegerField(blank=True, help_text='Actual Bags Used', null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='hours',
            field=models.IntegerField(blank=True, help_text='Actual Hours Worked', null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='persons',
            field=models.IntegerField(blank=True, help_text='Actual Persons', null=True),
        ),
    ]
