# Generated by Django 4.2.6 on 2023-11-09 15:55

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_assignment_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEvent',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('state', django_fsm.FSMIntegerField(choices=[(-40, 'Blocked'), (-30, 'Archived'), (-20, 'Cancelled'), (-10, 'Excluded'), (0, 'New'), (10, 'Included'), (20, 'Confirmed'), (30, 'Checked-In'), (40, 'Missed'), (50, 'Complete')], default=0)),
                ('comments', models.TextField(blank=True, default='', help_text='Please add any other notes you think we should know.', max_length=2000)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal (private) notes.', max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_events', to='app.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_events', to='app.team')),
            ],
        ),
        migrations.CreateModel(
            name='RecipientEvent',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('state', django_fsm.FSMIntegerField(choices=[(-40, 'Blocked'), (-30, 'Archived'), (-20, 'Cancelled'), (-10, 'Excluded'), (0, 'New'), (10, 'Included'), (20, 'Confirmed'), (30, 'Checked-In'), (40, 'Missed'), (50, 'Complete')], default=0)),
                ('comments', models.TextField(blank=True, default='', help_text='Please add any other notes you think we should know.', max_length=2000)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal (private) notes.', max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_events', to='app.event')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_events', to='app.recipient')),
            ],
        ),
    ]
