# Generated by Django 5.1.1 on 2024-09-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_recipient_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='location',
            field=models.CharField(default='', help_text='Please provide the street address to be raked (City of Eagle is assumed).', max_length=512),
        ),
    ]
