# Generated by Django 3.2.7 on 2021-10-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211002_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raccount', to='app.account', unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccount', to='app.account', unique=True),
        ),
    ]
