# Generated by Django 3.2.9 on 2021-11-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_volunteer_admin_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='size',
            field=models.IntegerField(choices=[(105, 'Solo (1 Adult)'), (110, 'Extra-Small (2-5 Adults)'), (120, 'Small (6-10 Adults)'), (130, 'Medium (11-15 Adults)'), (140, 'Large (16-20 Adults)'), (150, 'Extra-Large (21+ Adults)')], help_text='The size of your group. (Number of adults, or equivalent in children.)'),
        ),
    ]
