# Generated by Django 3.2.7 on 2021-10-02 13:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20211002_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='geocode',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='is_precise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipient',
            name='location',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='recipient',
            name='place',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipient',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
