# Generated by Django 3.1.3 on 2020-11-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20201116_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='persons',
        ),
        migrations.AddField(
            model_name='recipient',
            name='adults',
            field=models.IntegerField(blank=True, help_text='Actual Adults', null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='children',
            field=models.IntegerField(blank=True, help_text='Actual Children', null=True),
        ),
    ]
