# Generated by Django 4.2.6 on 2023-11-09 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_teamevent_recipientevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='team',
        ),
        migrations.AddField(
            model_name='assignment',
            name='recipient_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.recipientevent'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='team_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.teamevent'),
        ),
    ]
