# Generated by Django 3.2.9 on 2021-11-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_volunteer_size'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignment',
            name='unique_assignment',
        ),
    ]
