# Generated by Django 4.2.6 on 2023-11-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_assignment_recipient_remove_assignment_team_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipientEvent',
            new_name='Yard',
        ),
    ]
