# Generated by Django 3.1.3 on 2020-11-29 12:38

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('app', '0018_auto_20201117_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='addresss',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='address.address'),
        ),
    ]
