# Generated by Django 3.2.9 on 2021-11-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_assignment_unique_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
