# Generated by Django 4.2.6 on 2023-11-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_recipientevent_yard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamEvent',
            new_name='Rake',
        ),
    ]
