# Generated by Django 3.2.7 on 2021-10-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20211002_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='familiar_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='formal_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='greeting_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='nick_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='suffix',
        ),
    ]
