# Generated by Django 5.1.1 on 2024-09-26 22:19

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_team_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New'), (10, 'Sent'), (20, 'Read')], default=0),
        ),
    ]
