# Generated by Django 3.1.3 on 2020-11-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20201129_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='addresss',
            new_name='address',
        ),
    ]
