# Generated by Django 3.2.7 on 2021-10-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20211002_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='geocode',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_precise',
        ),
        migrations.RemoveField(
            model_name='account',
            name='place',
        ),
        migrations.RemoveField(
            model_name='account',
            name='point',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
    ]
