# Generated by Django 4.2.6 on 2023-11-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_teamevent_rake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='team_event',
            new_name='rake',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='recipient_event',
            new_name='yard',
        ),
        migrations.AlterField(
            model_name='rake',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rakes', to='app.event'),
        ),
        migrations.AlterField(
            model_name='rake',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rakes', to='app.team'),
        ),
        migrations.AlterField(
            model_name='yard',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yards', to='app.event'),
        ),
        migrations.AlterField(
            model_name='yard',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yards', to='app.recipient'),
        ),
    ]
