# Generated by Django 3.2.7 on 2021-10-03 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211002_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to='app.account'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='size',
            field=models.IntegerField(blank=True, choices=[(110, 'Small (1-15 bags)'), (120, 'Medium (16-30 bags)'), (130, 'Large (31+ bags)')], help_text='Yard Size'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer', to='app.account'),
        ),
    ]
