# Generated by Django 3.1.4 on 2020-12-01 16:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201129_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', help_text='Your phone.', max_length=255, region=None),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', help_text='Your mobile phone.', max_length=255, region=None),
        ),
    ]
