# Generated by Django 4.2.6 on 2023-11-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_team_event_assignment_rake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='rake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.rake'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='yard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.yard'),
        ),
    ]
