# Generated by Django 3.2.7 on 2021-10-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20211002_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='size',
            field=models.IntegerField(blank=True, choices=[(110, 'Small (1-15 bags)'), (120, 'Medium (16-30 bags)'), (130, 'Large (31+ bags)')], help_text='Yard Size', null=True),
        ),
    ]
