# Generated by Django 5.1.1 on 2024-10-03 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_assignment_id_alter_event_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='raw',
        ),
    ]
