# Generated by Django 3.1.4 on 2020-12-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20201201_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='first',
            field=models.CharField(blank=True, max_length=100, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='full',
            field=models.CharField(default='', max_length=100, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='last',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='middle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Middle name'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nickname'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='suffix',
            field=models.CharField(blank=True, max_length=100, verbose_name='Suffix'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='first',
            field=models.CharField(blank=True, max_length=100, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='full',
            field=models.CharField(default='', max_length=100, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='last',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='middle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Middle name'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nickname'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='suffix',
            field=models.CharField(blank=True, max_length=100, verbose_name='Suffix'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title'),
        ),
    ]
