# Generated by Django 3.2.9 on 2021-11-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20211126_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='app.event'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='app.event'),
        ),
    ]
