# Generated by Django 3.1.4 on 2020-12-01 17:07

from django.db import migrations

def forward(apps, schema_editor):
    Volunteer = apps.get_model('app', 'Volunteer')
    vs = Volunteer.objects.all()
    for v in vs:
        v.full = v.name
        v.save()

    Recipient = apps.get_model('app', 'Recipient')
    rs = Recipient.objects.all()
    for r in rs:
        r.full = r.name
        r.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20201201_0907'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
