# Generated by Django 4.2.6 on 2023-11-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rake_size_yard_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rake',
            name='size',
        ),
        migrations.RemoveField(
            model_name='yard',
            name='size',
        ),
    ]
