# Generated by Django 3.2.7 on 2021-10-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_recipient_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='is_dog',
            field=models.BooleanField(blank=True, help_text='If you have a dog, it must be contained in your home for us to rake.\xa0 Also, you must clean up all animal waste before we arrive or our volunteer group will not be able to rake.'),
        ),
    ]
