# Generated by Django 5.1.1 on 2024-10-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_message_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='place_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='location',
            field=models.CharField(default='', max_length=512),
        ),
    ]
