# Generated by Django 3.2.9 on 2021-11-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20211126_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='event',
        ),
    ]
