# Generated by Django 5.1.1 on 2024-10-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_recipient_place_id_alter_recipient_location'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipient',
            constraint=models.UniqueConstraint(fields=('place_id', 'event'), name='unique_location_event'),
        ),
    ]
