# Generated by Django 4.2.6 on 2023-11-09 20:10

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_rake_size_remove_yard_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Blocked'), (0, 'New'), (10, 'Good')], default=0),
        ),
    ]
