# Generated by Django 3.2.9 on 2021-11-26 15:17

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_assignment_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Cancelled'), (0, 'New'), (10, 'Pending'), (20, 'Confirmed')], default=0),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Cancelled'), (0, 'New'), (10, 'Pending'), (20, 'Confirmed')], default=0),
        ),
    ]
