# Generated by Django 3.1.4 on 2020-12-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20201201_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='name',
            new_name='namer',
        ),
    ]
