# Generated by Django 5.1.1 on 2024-10-03 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_recipient_unique_location_event'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipient',
            name='unique_recipient_event',
        ),
    ]
