# Generated by Django 3.2.9 on 2021-11-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20211126_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='account',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='account',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='account',
        ),
    ]
