# Generated by Django 3.1.4 on 2020-12-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20201201_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='first',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='full',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='last',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='middle',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='suffix',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='title',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='first',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='full',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='last',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='middle',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='suffix',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='title',
        ),
    ]
