# Generated by Django 5.1.1 on 2024-10-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_recipient_state_alter_team_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='deadline',
        ),
    ]
