# Generated by Django 3.2.9 on 2021-11-26 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_delete_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='email',
        ),
        migrations.AddField(
            model_name='picture',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='app.event'),
        ),
    ]
