# Generated by Django 4.2.6 on 2023-11-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_assignment_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
