# Generated by Django 3.1.4 on 2020-12-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20201201_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='familiar_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Familiar Name'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='formal_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Formal Name'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='long_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Long Name'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Short Name'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='familiar_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Familiar Name'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='formal_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Formal Name'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='long_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Long Name'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Short Name'),
        ),
    ]
