# Generated by Django 3.1.4 on 2020-12-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20201201_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='full_name',
        ),
    ]
