# Generated by Django 5.1.1 on 2024-10-23 23:16

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_message_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(-50, 'Archived'), (50, 'Cancelled'), (40, 'Declined'), (0, 'New'), (5, 'Invited'), (7, 'Accepted'), (20, 'Confirmed'), (30, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(-50, 'Archived'), (50, 'Cancelled'), (40, 'Declined'), (0, 'New'), (5, 'Invited'), (7, 'Accepted'), (20, 'Confirmed'), (30, 'Completed')], default=0),
        ),
    ]
