# Generated by Django 3.1.4 on 2020-12-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20201201_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='long_name',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='long_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='short_name',
        ),
        migrations.AddField(
            model_name='recipient',
            name='greeting_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Greeting Name'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='greeting_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Greeting Name'),
        ),
    ]
