# Generated by Django 3.2.9 on 2021-11-27 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20211126_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('state', django_fsm.FSMIntegerField(choices=[(0, 'New'), (10, 'Sent')], default=0)),
                ('sid', models.CharField(blank=True, max_length=100)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('body', models.TextField(blank=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('state', django_fsm.FSMIntegerField(choices=[(0, 'New'), (10, 'Active'), (20, 'Inactive'), (30, 'Closed')], default=0)),
                ('friendly_name', models.CharField(blank=True, default='', max_length=256)),
                ('sid', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('sid', models.CharField(blank=True, max_length=100)),
                ('messaging_binding', models.JSONField(blank=True, null=True)),
                ('last_read_message_index', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='app.comment')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.conversation')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.conversation'),
        ),
        migrations.AddField(
            model_name='comment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.participant'),
        ),
    ]
