# Generated by Django 4.2.6 on 2023-11-10 04:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_user_data_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='rake',
            name='actual',
            field=models.IntegerField(blank=True, help_text='The actual number of adults, or adult-equivalent in children.', null=True),
        ),
        migrations.AddField(
            model_name='rake',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text="Whimsical Team Name (ie, Robert's Rakers, Covey Courters, etc.)", max_length=100),
        ),
        migrations.AddField(
            model_name='rake',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='rake',
            name='size',
            field=models.IntegerField(blank=True, choices=[(105, 'Solo (1 Adult)'), (110, 'Extra-Small (2-5 Adults)'), (120, 'Small (6-10 Adults)'), (130, 'Medium (11-15 Adults)'), (140, 'Large (16-20 Adults)'), (150, 'Extra-Large (21+ Adults)')], null=True),
        ),
    ]
