# Generated by Django 5.1.1 on 2024-10-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_recipient_state_alter_team_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='admin_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='admin_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='admin_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='admin_notes',
            new_name='notes',
        ),
    ]
