# Generated by Django 3.2.9 on 2021-11-27 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20211126_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-phone',)},
        ),
    ]
