# Generated by Django 4.2.6 on 2023-11-10 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_rake_actual_rake_nickname_rake_phone_rake_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='rake',
            name='name',
            field=models.CharField(blank=True, default='', help_text="Whimsical Team Name (ie, Robert's Rakers, Covey Courters, etc.)", max_length=100),
        ),
        migrations.AlterField(
            model_name='rake',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rakes', to='app.team'),
        ),
    ]
