# Generated by Django 3.2.9 on 2021-11-27 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('phone',)},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='comment',
        ),
    ]
