# Generated by Django 4.2.7 on 2023-11-10 05:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_rake_name_alter_rake_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='yard',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
