# Generated by Django 5.1.1 on 2024-10-24 12:50

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_assignment_public_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(-50, 'Archived'), (0, 'New'), (5, 'Invited'), (7, 'Accepted'), (20, 'Confirmed'), (30, 'Completed'), (40, 'Declined'), (50, 'Cancelled')], default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(-50, 'Archived'), (0, 'New'), (5, 'Invited'), (7, 'Accepted'), (20, 'Confirmed'), (30, 'Completed'), (40, 'Declined'), (50, 'Cancelled')], default=0),
        ),
    ]
