# Generated by Django 3.2.9 on 2021-11-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20211126_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='last_read_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
