# Generated by Django 3.2.9 on 2021-11-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_participant_last_read_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='raw',
            new_name='delivery',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True, max_length=1600),
        ),
    ]
