# Generated by Django 4.2.7 on 2023-11-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_rename_notes_recipient_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='comments',
            new_name='public_notes',
        ),
        migrations.RenameField(
            model_name='rake',
            old_name='comments',
            new_name='public_notes',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='comments',
            new_name='public_notes',
        ),
        migrations.RenameField(
            model_name='yard',
            old_name='comments',
            new_name='public_notes',
        ),
    ]
