# Generated by Django 3.1.4 on 2020-12-01 20:51

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20201201_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, upload_to=app.models.UploadPath('image')),
        ),
    ]
