# Generated by Django 5.1.1 on 2024-11-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_event_state_alter_recipient_state_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('year',), name='unique_event_year'),
        ),
    ]
