# Generated by Django 3.2.9 on 2021-11-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20211126_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='account',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='account',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
