# Generated by Django 4.2.7 on 2023-11-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_rename_comments_assignment_public_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='notes',
            new_name='admin_notes',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='notes',
            new_name='admin_notes',
        ),
        migrations.RenameField(
            model_name='rake',
            old_name='notes',
            new_name='admin_notes',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='notes',
            new_name='public_notes',
        ),
        migrations.RenameField(
            model_name='yard',
            old_name='notes',
            new_name='admin_notes',
        ),
    ]
