# Generated by Django 5.1.1 on 2024-11-07 02:50

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_assignment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(-20, 'Failed'), (-10, 'Cancelled'), (0, 'New'), (10, 'Assigned'), (40, 'Started'), (50, 'Finished')], default=0),
        ),
    ]
