# Generated by Django 4.2.7 on 2023-11-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_rename_notes_assignment_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='address',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
