# Generated by Django 5.1.3 on 2024-11-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_assignment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='assign_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recipient',
            name='complete_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
