# Generated by Django 3.2.9 on 2021-11-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='state',
        ),
    ]
