# Generated by Django 4.2.7 on 2023-11-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_recipient_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='yard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='yard',
            name='phone',
        ),
    ]
