# Generated by Django 3.2.9 on 2021-11-27 15:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_account_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.account')),
                ('state', django_fsm.FSMIntegerField(choices=[(-20, 'Cancelled'), (-10, 'Excluded'), (0, 'New'), (10, 'Included'), (20, 'Confirmed')], default=0)),
                ('size', models.IntegerField(blank=True, choices=[(110, 'Small (1-15 bags)'), (120, 'Medium (16-30 bags)'), (130, 'Large (31+ bags)')], help_text='Please provide the approximate yard size.')),
                ('location', models.CharField(blank=True, default='', help_text='Please provide the location address to be raked.', max_length=512)),
                ('place', models.CharField(blank=True, default='', max_length=255)),
                ('is_precise', models.BooleanField(default=False)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('geocode', models.JSONField(blank=True, null=True)),
                ('is_dog', models.BooleanField(blank=True, default=False, help_text='If you have a dog, it must be contained in your home for us to rake. <em>Also, you must clean up all animal waste before we arrive or our team group will not be able to rake.</em>')),
                ('notes', models.TextField(blank=True, default='', help_text='Please add any other notes you think we should know.', max_length=2000)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Administrator Notes (from calling).', max_length=2000)),
                ('bags', models.IntegerField(blank=True, help_text='Actual Bags Used', null=True)),
                ('hours', models.FloatField(blank=True, help_text='Actual Hours Worked', null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.account',),
        ),
        migrations.CreateModel(
            name='TeamAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.account')),
                ('state', django_fsm.FSMIntegerField(choices=[(-20, 'Cancelled'), (-10, 'Excluded'), (0, 'New'), (10, 'Included'), (20, 'Confirmed')], default=0)),
                ('size', models.IntegerField(choices=[(105, 'Solo (1 Adult)'), (110, 'Extra-Small (2-5 Adults)'), (120, 'Small (6-10 Adults)'), (130, 'Medium (11-15 Adults)'), (140, 'Large (16-20 Adults)'), (150, 'Extra-Large (21+ Adults)')], help_text='The size of your group. (Number of adults, or equivalent in children.)')),
                ('team', models.CharField(blank=True, default='', help_text="Whimsical Team Name (ie, Robert's Rakers, Covey Courters, etc.)", max_length=100)),
                ('reference', models.CharField(blank=True, default='', help_text='How did you hear about us?', max_length=512)),
                ('actual', models.IntegerField(blank=True, help_text='The actual number of adults, or adult-equivalent in children.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes.', max_length=512)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Administrator Notes (from calling).', max_length=2000)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.account',),
        ),
    ]
