# Generated by Django 5.1.3 on 2024-11-07 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_recipient_assign_code_recipient_complete_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='app.team'),
        ),
    ]
