# Generated by Django 4.2.7 on 2023-11-10 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_recipient_name_remove_recipient_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
