# Generated by Django 3.2.9 on 2021-11-27 15:40

from django.db import migrations

def forward(apps, schema_editor):
    RecipientAccount = apps.get_model('app', 'RecipientAccount')
    Recipient = apps.get_model('app', 'Recipient')
    TeamAccount = apps.get_model('app', 'TeamAccount')
    Team = apps.get_model('app', 'Team')

    rs = Recipient.objects.all()
    for r in rs:
        RecipientAccount.objects.create(
            name=r.name,
            phone=r.phone,
            state=r.state,
            size=r.size,
            location=r.location,
            place=r.place,
            is_precise=r.is_precise,
            point=r.point,
            geocode=r.geocode,
            is_dog=r.is_dog,
            notes=r.notes,
            admin_notes=r.admin_notes,
            bags=r.bags,
            hours=r.hours,
            user=r.user,
        )

    ts = Team.objects.all()
    for t in ts:
        TeamAccount.objects.create(
            name=t.name,
            phone=t.phone,
            state=t.state,
            size=t.size,
            team=t.team,
            reference=t.reference,
            actual=t.actual,
            notes=t.notes,
            admin_notes=t.admin_notes,
            user=t.user,
        )



class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_recipientaccount_teamaccount'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
