# Generated by Django 4.2.7 on 2023-11-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_team_name_remove_team_phone_alter_team_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rake',
            name='actual',
        ),
        migrations.RemoveField(
            model_name='rake',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rake',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='rake',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='rake',
            name='size',
        ),
    ]
