# Generated by Django 4.2.7 on 2023-11-10 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_rake_actual_remove_rake_name_and_more'),
    ]

    operations = [
        migrations.RenameModel("Message", "MessageArchive")
    ]
