# Generated by Django 4.2.7 on 2023-11-11 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import hashid_field.field
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_messagearchive_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=100, null=True, unique=True)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'New'), (10, 'Active')], default=0)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.CharField(blank=True, default='', max_length=1600)),
                ('components', models.JSONField(blank=True, null=True)),
                ('variables', models.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=100, null=True, unique=True)),
                ('state', django_fsm.FSMIntegerField(choices=[(10, 'active'), (-10, 'inactive'), (-20, 'closed')], default=10)),
                ('friendly_name', models.CharField(max_length=100, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=100, null=True, unique=True)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, max_length=1600, null=True)),
                ('media', models.JSONField(blank=True, max_length=2048, null=True)),
                ('delivery', models.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.ForeignKey(blank=True, db_column='content_sid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='app.content', to_field='sid')),
                ('conversation', models.ForeignKey(db_column='conversation_sid', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.conversation', to_field='sid')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=100, null=True, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_read_message_index', models.IntegerField(blank=True, null=True)),
                ('last_read_timestamp', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(db_column='conversation_sid', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.conversation', to_field='sid')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=100, null=True, unique=True)),
                ('status', django_fsm.FSMIntegerField(choices=[(-20, 'failed'), (-10, 'undelivered'), (0, 'sent'), (20, 'delivered'), (30, 'read')])),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('conversation', models.ForeignKey(db_column='conversation_sid', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='app.conversation', to_field='sid')),
                ('message', models.ForeignKey(db_column='message_sid', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='app.message', to_field='sid')),
                ('participant', models.ForeignKey(db_column='participation_sid', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='app.participant', to_field='sid')),
            ],
        ),
    ]
