# Generated by Django 4.2.7 on 2023-11-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_content_conversation_message_participant_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='sid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='sid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='sid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='sid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
