# Generated by Django 4.2.7 on 2023-11-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_content_sid_alter_conversation_sid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='friendly_name',
            new_name='name',
        ),
    ]
