# Generated by Django 4.2.7 on 2023-11-11 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_rename_friendly_name_conversation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.AddField(
            model_name='assignment',
            name='conversation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='app.conversation'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='conversation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='app.conversation'),
        ),
        migrations.AddField(
            model_name='team',
            name='conversation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='app.conversation'),
        ),
    ]
