# Generated by Django 4.2.7 on 2023-11-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_assignment_recipient_assignment_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='rake',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='yard',
        ),
    ]
