# Generated by Django 4.2.7 on 2023-11-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_assignment_recipient_assignment_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yard',
            name='event',
        ),
        migrations.RemoveField(
            model_name='yard',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='rake',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='yard',
        ),
        migrations.DeleteModel(
            name='Rake',
        ),
        migrations.DeleteModel(
            name='Yard',
        ),
    ]
