# Generated by Django 4.2.7 on 2023-11-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_remove_assignment_rake_remove_assignment_yard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yard',
            name='event',
        ),
        migrations.RemoveField(
            model_name='yard',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='Rake',
        ),
        migrations.DeleteModel(
            name='Yard',
        ),
    ]
