# Generated by Django 4.2.7 on 2023-11-13 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_remove_yard_event_remove_yard_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='team',
            name='conversation',
        ),
        migrations.AddField(
            model_name='user',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='app.conversation'),
        ),
    ]
