# Generated by Django 4.2.7 on 2023-11-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_remove_assignment_conversation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='conversation',
        ),
    ]
