# Generated by Django 4.2.7 on 2023-11-13 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_remove_user_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to=settings.AUTH_USER_MODEL),
        ),
    ]
