# Generated by Django 4.2.7 on 2023-11-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_conversation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='address',
        ),
    ]
