# Generated by Django 4.2.7 on 2023-11-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_remove_recipient_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='actual',
            new_name='adults',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='bags',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='hours',
        ),
        migrations.AlterField(
            model_name='recipient',
            name='bags',
            field=models.IntegerField(blank=True, help_text='Bags estimate', null=True),
        ),
    ]
