name: Deploy MkDocs Site
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Checkout the repository
      - uses: actions/setup-python@v5 # Set up Python
        with:
          python-version: '3.13' # Specify a Python version
      - name: Install MkDocs and Material theme
        run: |
          pip install mkdocs mkdocs-material
      - name: Deploy MkDocs site to GitHub Pages
        run: mkdocs gh-deploy --force # Build and deploy to gh-pages branch
