name: Deploy to GitHub Pages
on:
  push:
    branches: ["pelican"]
  workflow_dispatch:
jobs:
  deploy:
    uses: "getpelican/pelican/.github/workflows/github_pages.yml@master"
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    with:
      settings: "pelicanconf.py"
      requirements: "pelican markdown typogrify beautifulsoup4"
